name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]*'
  workflow_dispatch:
    inputs:
      publish_without_testing:
        description: 'Publicar sin correr los tests'
        type: boolean
        required: false
        default: false

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    uses: codenautas/.github/.github/workflows/npm-publish-new-version.yaml@v3
    with:
      node_version: '24.x'
      publish_without_testing: ${{ inputs.publish_without_testing == true }}
      postgres: ''
      create-tag: ${{ github.event_name == 'workflow_dispatch' }}
